export const SEARCH_KEYWORD = "SEARCH_KEYWORD";
export const ADD_SEARCH_KEYWORD = "ADD_SEARCH_KEYWORD";
export const CLEAR_SEARCH_KEYWORD = "CLEAR_SEARCH_KEYWORD";
export const FETCH_MOVIES_BY_KEYWORD = "FETCH_MOVIES_BY_KEYWORD";
