const data = [
  {
    adult: false,
    backdrop_path: '/mSyQoValhBsJdq3JNGXJww2Q5yL.jpg',
    id: 593643,
    title: 'The Menu',
    original_language: 'en',
    original_title: 'The Menu',
    overview:
      'A couple travels to a coastal island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.',
    poster_path: '/fPtUgMcLIboqlTlPrq0bQpKK8eq.jpg',
    media_type: 'movie',
    genre_ids: [53, 27, 35],
    popularity: 612.165,
    release_date: '2022-11-17',
    video: false,
    vote_average: 7.307,
    vote_count: 750,
  },
  {
    adult: false,
    backdrop_path: '/5gPQKfFJnl8d1edbkOzKONo4mnr.jpg',
    id: 76600,
    title: 'Avatar: The Way of Water',
    original_language: 'en',
    original_title: 'Avatar: The Way of Water',
    overview:
      'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    media_type: 'movie',
    genre_ids: [878, 12, 28],
    popularity: 4718.023,
    release_date: '2022-12-14',
    video: false,
    vote_average: 7.699,
    vote_count: 3571,
  },
  {
    adult: false,
    backdrop_path: '/kSqEenES71d1ApF2rRWxp5X0en5.jpg',
    id: 156902,
    name: 'Kaleidoscope',
    original_language: 'en',
    original_name: 'Kaleidoscope',
    overview:
      'A master thief and his crew attempt an epic and elaborate heist worth $7 billion dollars — but betrayal, greed and other threats undermine their plans.',
    poster_path: '/2nXJoSB5Y6R9ne7pjqL7Cs3zqY1.jpg',
    media_type: 'tv',
    genre_ids: [80, 18],
    popularity: 216.002,
    first_air_date: '2023-01-01',
    vote_average: 7.372,
    vote_count: 39,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg',
    id: 661374,
    title: 'Glass Onion: A Knives Out Mystery',
    original_language: 'en',
    original_title: 'Glass Onion: A Knives Out Mystery',
    overview:
      'World-famous detective Benoit Blanc heads to Greece to peel back the layers of a mystery surrounding a tech billionaire and his eclectic crew of friends.',
    poster_path: '/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg',
    media_type: 'movie',
    genre_ids: [9648, 53, 35],
    popularity: 3751.901,
    release_date: '2022-11-23',
    video: false,
    vote_average: 7.091,
    vote_count: 2124,
  },
  {
    adult: false,
    backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
    id: 436270,
    title: 'Black Adam',
    original_language: 'en',
    original_title: 'Black Adam',
    overview:
      'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
    poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
    media_type: 'movie',
    genre_ids: [28, 14, 878],
    popularity: 2699.078,
    release_date: '2022-10-19',
    video: false,
    vote_average: 7.22,
    vote_count: 3519,
  },
  {
    adult: false,
    backdrop_path: '/sjxtIUCWR74yPPcZFfTsToepfWm.jpg',
    id: 105971,
    name: 'Star Wars: The Bad Batch',
    original_language: 'en',
    original_name: 'Star Wars: The Bad Batch',
    overview:
      "The 'Bad Batch' of elite and experimental clones make their way through an ever-changing galaxy in the immediate aftermath of the Clone Wars.",
    poster_path: '/5Q6z9bjy8dHKA5T8kNmCd8hj6Gl.jpg',
    media_type: 'tv',
    genre_ids: [16, 10759, 10765],
    popularity: 188.45,
    first_air_date: '2021-05-04',
    vote_average: 8.355,
    vote_count: 683,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/1cRFirFoqYQ31vx8rxt2GlPZBVS.jpg',
    id: 206510,
    name: 'Copenhagen Cowboy',
    original_language: 'da',
    original_name: 'Copenhagen Cowboy',
    overview:
      'After a lifetime of servitude and on the verge of a new beginning, Miu traverses the ominous landscape of Copenhagen’s criminal netherworld. Searching for justice and enacting vengeance, she encounters her nemesis, Rakel, as they embark on an odyssey through the natural and the supernatural. The past ultimately transforms and defines their future, as the two women discover they are not alone, they are many.',
    poster_path: '/rjzlyPQdEPL0OiLOqxZi91Tl8aG.jpg',
    media_type: 'tv',
    genre_ids: [80, 18],
    popularity: 50.27,
    first_air_date: '2023-01-05',
    vote_average: 6,
    vote_count: 5,
    origin_country: ['DK'],
  },
];
export default data;
